<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Librarian.Domain\Librarian.Domain.csproj" />
    <ProjectReference Include="..\Librarian.Infrastucture\Librarian.Infrastucture.csproj" />
  </ItemGroup>

</Project>
